### ISSUE TITLE
Add ServiceWorker to allow offline

### ISSUE THREAD

**Issue by coogie** [coogie/whatismyviewport#23]
Once the migration to HTTPS happens, a Service Worker should be added to the site to allow it to function offline.

For reasons...

**Comment by vitokhangnguyen** [comment]
This is a very cool idea and I do not see why this app should need an internet connection.
I would like to work on this issue!

**Comment by coogie** [comment]
@vitokhangnguyen Have fun!

**Comment by vitokhangnguyen** [comment]
Hi,
I have successfully made the app work offline and installable. I also added [a tool ](https://developers.google.com/web/updates/2016/07/offline-google-analytics) to handle Google Tag Manager when the app's offline.
I would like to wait for a few more days before making a PR so it would be count in Hacktoberfest.

**Comment by coogie** [comment]
Hi @vitokhangnguyen 

That's fine :)
Just a quick heads up that the site has been migrated to Jekyll today, and this might impact you. Luckily, there's nothing overly complex with the new setup and is should be just as easy to apply your changes.

If you need any advice, just let me know :)

**Comment by vitokhangnguyen** [comment]
@coogie 

Hi, I did not see your message before making the PR #31 
I will look into it and add commits to try to get my part work with Jekyll.
